# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-02 16:35
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('redmine_tracker', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='redmine_story_id',
            field=models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(999999)]),
        ),
        migrations.AddField(
            model_name='task',
            name='redmine_story_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
