# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-02 18:37
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('redmine_tracker', '0002_auto_20170502_1235'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='redmine_user_id',
            field=models.PositiveIntegerField(default='0', validators=[django.core.validators.MaxValueValidator(999999)]),
            preserve_default=False,
        ),
    ]
