# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-08-25 19:20
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('redmine_tracker', '0004_auto_20170502_1516'),
    ]

    operations = [
        migrations.AddField(
            model_name='timebank',
            name='start',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='redmine_user_id',
            field=models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(999999)]),
        ),
    ]
