# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-08-25 20:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('redmine_tracker', '0005_auto_20170825_1520'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='is_hidden',
            field=models.BooleanField(default=False),
        ),
    ]
