# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-08-25 20:53
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('redmine_tracker', '0006_project_is_hidden'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='redmine_story_name',
            new_name='task_name',
        ),
        migrations.RemoveField(
            model_name='project',
            name='project_type',
        ),
        migrations.RemoveField(
            model_name='task',
            name='redmine_story_id',
        ),
        migrations.RemoveField(
            model_name='task',
            name='redmine_task_id',
        ),
        migrations.AddField(
            model_name='task',
            name='task_id',
            field=models.PositiveIntegerField(default='1', validators=[django.core.validators.MaxValueValidator(999999)]),
            preserve_default=False,
        ),
    ]
